version = 3.8.0
runner.dialect = scala3
maxColumn = 100
align.preset = false
assumeStandardLibraryStripMargin = true
align.stripMargin = true
danglingParentheses.preset = true
rewrite.rules = [SortImports]
importSelectors = singleLine
binPack.parentConstructors = true
includeCurlyBraceInSelectChains = false
