package io.octopus.sql.parser.dialect

import com.google.common.base.CharMatcher
import enumeratum.*
import io.octopus.sql.parser.dialect.PrestoDB.KeyWords
import io.octopus.sql.utils.Engine.OCTOPUS

class Octopus extends SqlDialect(engine = OCTOPUS) {

  override def partOfIdentifier(c: Char): Boolean = {
    CharMatcher.javaLetterOrDigit().matches(c)
      || c == '_'
      || c == '@'
      || c == ':'
  }

  override def startOfDelimitedIdentifier(c: Char):Boolean ={
    (c == '"') || (c == '`')
  }

  override def startOfIdentifier(c: Char): Boolean = {
    CharMatcher.javaLetterOrDigit().matches(c)
      || c == '_'
  }

  override def startOfQuotedIdentifier(c: Char): Boolean = {
    c == '"'
  }

  override def matchKeyWord(s: String): Option[String] = {
    KeyWords.withNameInsensitiveOption(s).map(x=>x.entryName)
  }
}

object Octopus:
  sealed trait KeyWord(override val entryName: String) extends EnumEntry

  object KeyWords extends Enum[KeyWord] {
    val values: IndexedSeq[KeyWord] = findValues

    case object ADD extends KeyWord("ADD")
    case object ADMIN extends KeyWord("ADMIN")
    case object ALL extends KeyWord("ALL")
    case object ALTER extends KeyWord("ALTER")
    case object ANALYZE extends KeyWord("ANALYZE")
    case object AND extends KeyWord("AND")
    case object ANY extends KeyWord("ANY")
    case object ARRAY extends KeyWord("ARRAY")
    case object AS extends KeyWord("AS")
    case object ASC extends KeyWord("ASC")
    case object AT extends KeyWord("AT")
    case object BERNOULLI extends KeyWord("BERNOULLI")
    case object BETWEEN extends KeyWord("BETWEEN")
    case object BY extends KeyWord("BY")
    case object CALL extends KeyWord("CALL")
    case object CALLED extends KeyWord("CALLED")
    case object CASCADE extends KeyWord("CASCADE")
    case object CASE extends KeyWord("CASE")
    case object CAST extends KeyWord("CAST")
    case object CATALOGS extends KeyWord("CATALOGS")
    case object COLUMN extends KeyWord("COLUMN")
    case object COLUMNS extends KeyWord("COLUMNS")
    case object COMMENT extends KeyWord("COMMENT")
    case object COMMIT extends KeyWord("COMMIT")
    case object COMMITTED extends KeyWord("COMMITTED")
    case object CONSTRAINT extends KeyWord("CONSTRAINT")
    case object CREATE extends KeyWord("CREATE")
    case object CROSS extends KeyWord("CROSS")
    case object CUBE extends KeyWord("CUBE")
    case object CURRENT extends KeyWord("CURRENT")
    case object CURRENT_DATE extends KeyWord("CURRENT_DATE")
    case object CURRENT_ROLE extends KeyWord("CURRENT_ROLE")
    case object CURRENT_TIME extends KeyWord("CURRENT_TIME")
    case object CURRENT_TIMESTAMP extends KeyWord("CURRENT_TIMESTAMP")
    case object CURRENT_USER extends KeyWord("CURRENT_USER")
    case object DATA extends KeyWord("DATA")
    case object DATE extends KeyWord("DATE")
    case object DAY extends KeyWord("DAY")
    case object DEALLOCATE extends KeyWord("DEALLOCATE")
    case object DEFINER extends KeyWord("DEFINER")
    case object DELETE extends KeyWord("DELETE")
    case object DESC extends KeyWord("DESC")
    case object DESCRIBE extends KeyWord("DESCRIBE")
    case object DETERMINISTIC extends KeyWord("DETERMINISTIC")
    case object DISTINCT extends KeyWord("DISTINCT")
    case object DISTRIBUTED extends KeyWord("DISTRIBUTED")
    case object DROP extends KeyWord("DROP")
    case object ELSE extends KeyWord("ELSE")
    case object END extends KeyWord("END")
    case object ESCAPE extends KeyWord("ESCAPE")
    case object EXCEPT extends KeyWord("EXCEPT")
    case object EXCLUDING extends KeyWord("EXCLUDING")
    case object EXECUTE extends KeyWord("EXECUTE")
    case object EXISTS extends KeyWord("EXISTS")
    case object EXPLAIN extends KeyWord("EXPLAIN")
    case object EXTRACT extends KeyWord("EXTRACT")
    case object EXTERNAL extends KeyWord("EXTERNAL")
    case object FALSE extends KeyWord("FALSE")
    case object FETCH extends KeyWord("FETCH")
    case object FILTER extends KeyWord("FILTER")
    case object FIRST extends KeyWord("FIRST")
    case object FOLLOWING extends KeyWord("FOLLOWING")
    case object FOR extends KeyWord("FOR")
    case object FORMAT extends KeyWord("FORMAT")
    case object FROM extends KeyWord("FROM")
    case object FULL extends KeyWord("FULL")
    case object FUNCTION extends KeyWord("FUNCTION")
    case object FUNCTIONS extends KeyWord("FUNCTIONS")
    case object GRANT extends KeyWord("GRANT")
    case object GRANTED extends KeyWord("GRANTED")
    case object GRANTS extends KeyWord("GRANTS")
    case object GRAPHVIZ extends KeyWord("GRAPHVIZ")
    case object GROUP extends KeyWord("GROUP")
    case object GROUPING extends KeyWord("GROUPING")
    case object GROUPS extends KeyWord("GROUPS")
    case object HAVING extends KeyWord("HAVING")
    case object HOUR extends KeyWord("HOUR")
    case object IF extends KeyWord("IF")
    case object IGNORE extends KeyWord("IGNORE")
    case object IN extends KeyWord("IN")
    case object INCLUDING extends KeyWord("INCLUDING")
    case object INNER extends KeyWord("INNER")
    case object INPUT extends KeyWord("INPUT")
    case object INSERT extends KeyWord("INSERT")
    case object INTERSECT extends KeyWord("INTERSECT")
    case object INTERVAL extends KeyWord("INTERVAL")
    case object INTO extends KeyWord("INTO")
    case object INVOKER extends KeyWord("INVOKER")
    case object IO extends KeyWord("IO")
    case object IS extends KeyWord("IS")
    case object ISOLATION extends KeyWord("ISOLATION")
    case object JSON extends KeyWord("JSON")
    case object JOIN extends KeyWord("JOIN")
    case object LANGUAGE extends KeyWord("LANGUAGE")
    case object LAST extends KeyWord("LAST")
    case object LATERAL extends KeyWord("LATERAL")
    case object LEFT extends KeyWord("LEFT")
    case object LEVEL extends KeyWord("LEVEL")
    case object LIKE extends KeyWord("LIKE")
    case object LIMIT extends KeyWord("LIMIT")
    case object LOCALTIME extends KeyWord("LOCALTIME")
    case object LOCALTIMESTAMP extends KeyWord("LOCALTIMESTAMP")
    case object LOGICAL extends KeyWord("LOGICAL")
    case object MAP extends KeyWord("MAP")
    case object MATERIALIZED extends KeyWord("MATERIALIZED")
    case object MINUTE extends KeyWord("MINUTE")
    case object MONTH extends KeyWord("MONTH")
    case object NAME extends KeyWord("NAME")
    case object NATURAL extends KeyWord("NATURAL")
    case object NFC extends KeyWord("NFC")
    case object NFD extends KeyWord("NFD")
    case object NFKC extends KeyWord("NFKC")
    case object NFKD extends KeyWord("NFKD")
    case object NO extends KeyWord("NO")
    case object NONE extends KeyWord("NONE")
    case object NORMALIZE extends KeyWord("NORMALIZE")
    case object NOT extends KeyWord("NOT")
    case object NULL extends KeyWord("NULL")
    case object NULLIF extends KeyWord("NULLIF")
    case object NULLS extends KeyWord("NULLS")
    case object OFFSET extends KeyWord("OFFSET")
    case object ON extends KeyWord("ON")
    case object ONLY extends KeyWord("ONLY")
    case object OPTION extends KeyWord("OPTION")
    case object OR extends KeyWord("OR")
    case object ORDER extends KeyWord("ORDER")
    case object ORDINALITY extends KeyWord("ORDINALITY")
    case object OUTER extends KeyWord("OUTER")
    case object OUTPUT extends KeyWord("OUTPUT")
    case object OVER extends KeyWord("OVER")
    case object PARTITION extends KeyWord("PARTITION")
    case object PARTITIONS extends KeyWord("PARTITIONS")
    case object POSITION extends KeyWord("POSITION")
    case object PRECEDING extends KeyWord("PRECEDING")
    case object PREPARE extends KeyWord("PREPARE")
    case object PRIVILEGES extends KeyWord("PRIVILEGES")
    case object PROPERTIES extends KeyWord("PROPERTIES")
    case object RANGE extends KeyWord("RANGE")
    case object READ extends KeyWord("READ")
    case object RECURSIVE extends KeyWord("RECURSIVE")
    case object REFRESH extends KeyWord("REFRESH")
    case object RENAME extends KeyWord("RENAME")
    case object REPEATABLE extends KeyWord("REPEATABLE")
    case object REPLACE extends KeyWord("REPLACE")
    case object RESET extends KeyWord("RESET")
    case object RESPECT extends KeyWord("RESPECT")
    case object RESTRICT extends KeyWord("RESTRICT")
    case object RETURN extends KeyWord("RETURN")
    case object RETURNS extends KeyWord("RETURNS")
    case object REVOKE extends KeyWord("REVOKE")
    case object RIGHT extends KeyWord("RIGHT")
    case object ROLE extends KeyWord("ROLE")
    case object ROLES extends KeyWord("ROLES")
    case object ROLLBACK extends KeyWord("ROLLBACK")
    case object ROLLUP extends KeyWord("ROLLUP")
    case object ROW extends KeyWord("ROW")
    case object ROWS extends KeyWord("ROWS")
    case object SCHEMA extends KeyWord("SCHEMA")
    case object SCHEMAS extends KeyWord("SCHEMAS")
    case object SECOND extends KeyWord("SECOND")
    case object SECURITY extends KeyWord("SECURITY")
    case object SELECT extends KeyWord("SELECT")
    case object SERIALIZABLE extends KeyWord("SERIALIZABLE")
    case object SESSION extends KeyWord("SESSION")
    case object SET extends KeyWord("SET")
    case object SETS extends KeyWord("SETS")
    case object SHOW extends KeyWord("SHOW")
    case object SOME extends KeyWord("SOME")
    case object SQL extends KeyWord("SQL")
    case object START extends KeyWord("START")
    case object STATS extends KeyWord("STATS")
    case object SUBSTRING extends KeyWord("SUBSTRING")
    case object SYSTEM extends KeyWord("SYSTEM")
    case object TABLE extends KeyWord("TABLE")
    case object TABLES extends KeyWord("TABLES")
    case object TABLESAMPLE extends KeyWord("TABLESAMPLE")
    case object TEMPORARY extends KeyWord("TEMPORARY")
    case object TEXT extends KeyWord("TEXT")
    case object THEN extends KeyWord("THEN")
    case object TIME extends KeyWord("TIME")
    case object TIMESTAMP extends KeyWord("TIMESTAMP")
    case object TO extends KeyWord("TO")
    case object TRANSACTION extends KeyWord("TRANSACTION")
    case object TRUE extends KeyWord("TRUE")
    case object TRUNCATE extends KeyWord("TRUNCATE")
    case object TRY_CAST extends KeyWord("TRY_CAST")
    case object TYPE extends KeyWord("TYPE")
    case object UESCAPE extends KeyWord("UESCAPE")
    case object UNBOUNDED extends KeyWord("UNBOUNDED")
    case object UNCOMMITTED extends KeyWord("UNCOMMITTED")
    case object UNION extends KeyWord("UNION")
    case object UNNEST extends KeyWord("UNNEST")
    case object USE extends KeyWord("USE")
    case object USER extends KeyWord("USER")
    case object USING extends KeyWord("USING")
    case object VALIDATE extends KeyWord("VALIDATE")
    case object VALUES extends KeyWord("VALUES")
    case object VERBOSE extends KeyWord("VERBOSE")
    case object VIEW extends KeyWord("VIEW")
    case object WHEN extends KeyWord("WHEN")
    case object WHERE extends KeyWord("WHERE")
    case object WITH extends KeyWord("WITH")
    case object WORK extends KeyWord("WORK")
    case object WRITE extends KeyWord("WRITE")
    case object YEAR extends KeyWord("YEAR")
    case object ZONE extends KeyWord("ZONE")
  }

end Octopus
