package io.octopus.sql.parser.dialect

import com.google.common.base.CharMatcher
import enumeratum.*
import io.octopus.sql.parser.token.{KeyWord, KeyWords}
import io.octopus.sql.utils.Engine.OCTOPUS

class Octopus extends SqlDialect(engine = OCTOPUS) {

  override def partOfIdentifier(c: Char): Boolean = {
    CharMatcher.javaLetterOrDigit().matches(c)
      || c == '_'
      || c == '@'
      || c == ':'
  }

  override def startOfDelimitedIdentifier(c: Char):Boolean ={
    (c == '"') || (c == '`')
  }

  override def startOfIdentifier(c: Char): Boolean = {
    CharMatcher.javaLetterOrDigit().matches(c)
      || c == '_'
  }

  override def matchKeyWord(s: String): Option[String] = {
    KeyWords.withNameInsensitiveOption(s).filter(x=>Octopus.KeyWordSet.contains(x)).map(x=>x.entryName)
  }


  override def matchReservedWords(s: String): Option[String] = {
    KeyWords.withNameInsensitiveOption(s).filter(x => Octopus.ReservedKeyWords.contains(x)).map(x => x.entryName)
  }
}

object Octopus:
  val KeyWordSet: Set[KeyWord] = Set(
    KeyWords.ADD,
    KeyWords.ADMIN,
    KeyWords.ALL,
    KeyWords.ALTER,
    KeyWords.ANALYZE,
    KeyWords.AND,
    KeyWords.ANY,
    KeyWords.ARRAY,
    KeyWords.AS,
    KeyWords.ASC,
    KeyWords.AT,
    KeyWords.BERNOULLI,
    KeyWords.BETWEEN,
    KeyWords.BY,
    KeyWords.CALL,
    KeyWords.CALLED,
    KeyWords.CASCADE,
    KeyWords.CASE,
    KeyWords.CAST,
    KeyWords.CATALOGS,
    KeyWords.COLUMN,
    KeyWords.COLUMNS,
    KeyWords.COMMENT,
    KeyWords.COMMIT,
    KeyWords.COMMITTED,
    KeyWords.CONSTRAINT,
    KeyWords.CREATE,
    KeyWords.CROSS,
    KeyWords.CUBE,
    KeyWords.CURRENT,
    KeyWords.CURRENT_DATE,
    KeyWords.CURRENT_ROLE,
    KeyWords.CURRENT_TIME,
    KeyWords.CURRENT_TIMESTAMP,
    KeyWords.CURRENT_USER,
    KeyWords.DATA,
    KeyWords.DATE,
    KeyWords.DAY,
    KeyWords.DEALLOCATE,
    KeyWords.DEFINER,
    KeyWords.DELETE,
    KeyWords.DESC,
    KeyWords.DESCRIBE,
    KeyWords.DETERMINISTIC,
    KeyWords.DISABLED,
    KeyWords.DISTINCT,
    KeyWords.DISTRIBUTED,
    KeyWords.DROP,
    KeyWords.ELSE,
    KeyWords.ENABLED,
    KeyWords.END,
    KeyWords.ENFORCED,
    KeyWords.ESCAPE,
    KeyWords.EXCEPT,
    KeyWords.EXCLUDING,
    KeyWords.EXECUTE,
    KeyWords.EXISTS,
    KeyWords.EXPLAIN,
    KeyWords.EXTRACT,
    KeyWords.EXTERNAL,
    KeyWords.FALSE,
    KeyWords.FETCH,
    KeyWords.FILTER,
    KeyWords.FIRST,
    KeyWords.FOLLOWING,
    KeyWords.FOR,
    KeyWords.FORMAT,
    KeyWords.FROM,
    KeyWords.FULL,
    KeyWords.FUNCTION,
    KeyWords.FUNCTIONS,
    KeyWords.GRANT,
    KeyWords.GRANTED,
    KeyWords.GRANTS,
    KeyWords.GRAPHVIZ,
    KeyWords.GROUP,
    KeyWords.GROUPING,
    KeyWords.GROUPS,
    KeyWords.HAVING,
    KeyWords.HOUR,
    KeyWords.IF,
    KeyWords.IGNORE,
    KeyWords.IN,
    KeyWords.INCLUDING,
    KeyWords.INNER,
    KeyWords.INPUT,
    KeyWords.INSERT,
    KeyWords.INTERSECT,
    KeyWords.INTERVAL,
    KeyWords.INTO,
    KeyWords.INVOKER,
    KeyWords.IO,
    KeyWords.IS,
    KeyWords.ISOLATION,
    KeyWords.JSON,
    KeyWords.JOIN,
    KeyWords.KEY,
    KeyWords.LANGUAGE,
    KeyWords.LAST,
    KeyWords.LATERAL,
    KeyWords.LEFT,
    KeyWords.LEVEL,
    KeyWords.LIKE,
    KeyWords.LIMIT,
    KeyWords.LOCALTIME,
    KeyWords.LOCALTIMESTAMP,
    KeyWords.LOGICAL,
    KeyWords.MAP,
    KeyWords.MATERIALIZED,
    KeyWords.MINUTE,
    KeyWords.MONTH,
    KeyWords.NAME,
    KeyWords.NATURAL,
    KeyWords.NFC ,
    KeyWords.NFD ,
    KeyWords.NFKC ,
    KeyWords.NFKD ,
    KeyWords.NO,
    KeyWords.NONE,
    KeyWords.NORMALIZE,
    KeyWords.NOT,
    KeyWords.NULL,
    KeyWords.NULLIF,
    KeyWords.NULLS,
    KeyWords.OF,
    KeyWords.OFFSET,
    KeyWords.ON,
    KeyWords.ONLY,
    KeyWords.OPTION,
    KeyWords.OR,
    KeyWords.ORDER,
    KeyWords.ORDINALITY,
    KeyWords.OUTER,
    KeyWords.OUTPUT,
    KeyWords.OVER,
    KeyWords.PARTITION,
    KeyWords.PARTITIONS,
    KeyWords.POSITION,
    KeyWords.PRECEDING,
    KeyWords.PREPARE,
    KeyWords.PRIMARY,
    KeyWords.PRIVILEGES,
    KeyWords.PROPERTIES,
    KeyWords.RANGE,
    KeyWords.READ,
    KeyWords.RECURSIVE,
    KeyWords.REFRESH,
    KeyWords.RELY,
    KeyWords.RENAME,
    KeyWords.REPEATABLE,
    KeyWords.REPLACE,
    KeyWords.RESET,
    KeyWords.RESPECT,
    KeyWords.RESTRICT,
    KeyWords.RETURN,
    KeyWords.RETURNS,
    KeyWords.REVOKE,
    KeyWords.RIGHT,
    KeyWords.ROLE,
    KeyWords.ROLES,
    KeyWords.ROLLBACK,
    KeyWords.ROLLUP,
    KeyWords.ROW,
    KeyWords.ROWS,
    KeyWords.SCHEMA,
    KeyWords.SCHEMAS,
    KeyWords.SECOND,
    KeyWords.SECURITY,
    KeyWords.SELECT,
    KeyWords.SERIALIZABLE,
    KeyWords.SESSION,
    KeyWords.SET,
    KeyWords.SETS,
    KeyWords.SHOW,
    KeyWords.SOME,
    KeyWords.SQL,
    KeyWords.START,
    KeyWords.STATS,
    KeyWords.SUBSTRING,
    KeyWords.SYSTEM,
    KeyWords.SYSTEM_TIME,
    KeyWords.SYSTEM_VERSION,
    KeyWords.TABLE,
    KeyWords.TABLES,
    KeyWords.TABLESAMPLE,
    KeyWords.TEMPORARY,
    KeyWords.TEXT,
    KeyWords.THEN,
    KeyWords.TIME,
    KeyWords.TIMESTAMP,
    KeyWords.TO,
    KeyWords.TRANSACTION,
    KeyWords.TRUE,
    KeyWords.TRUNCATE,
    KeyWords.TRY_CAST,
    KeyWords.TYPE,
    KeyWords.UESCAPE,
    KeyWords.UNBOUNDED,
    KeyWords.UNCOMMITTED,
    KeyWords.UNION,
    KeyWords.UNIQUE,
    KeyWords.UNNEST,
    KeyWords.UPDATE,
    KeyWords.USE,
    KeyWords.USER,
    KeyWords.USING,
    KeyWords.VALIDATE,
    KeyWords.VALUES,
    KeyWords.VERBOSE,
    KeyWords.VERSION,
    KeyWords.VIEW,
    KeyWords.WHEN,
    KeyWords.WHERE,
    KeyWords.WITH,
    KeyWords.WORK,
    KeyWords.WRITE,
    KeyWords.YEAR,
    KeyWords.ZONE
  )

  val ReservedKeyWords: Set[KeyWord] = Set(
    KeyWords.ALTER,
    KeyWords.AND,
    KeyWords.AS,
    KeyWords.BETWEEN,
    KeyWords.BY,
    KeyWords.CASE,
    KeyWords.CAST,
    KeyWords.CONSTRAINT,
    KeyWords.CREATE,
    KeyWords.CROSS,
    KeyWords.CUBE,
    KeyWords.CURRENT_DATE,
    KeyWords.CURRENT_TIME,
    KeyWords.CURRENT_TIMESTAMP,
    KeyWords.CURRENT_USER,
    KeyWords.DEALLOCATE,
    KeyWords.DELETE,
    KeyWords.DESCRIBE,
    KeyWords.DISTINCT,
    KeyWords.DROP,
    KeyWords.ELSE,
    KeyWords.END,
    KeyWords.ESCAPE,
    KeyWords.EXCEPT,
    KeyWords.EXECUTE,
    KeyWords.EXISTS,
    KeyWords.EXTRACT,
    KeyWords.FALSE,
    KeyWords.FOR,
    KeyWords.FROM,
    KeyWords.FULL,
    KeyWords.GROUP,
    KeyWords.GROUPING,
    KeyWords.HAVING,
    KeyWords.IN,
    KeyWords.INNER,
    KeyWords.INSERT,
    KeyWords.INTERSECT,
    KeyWords.INTO,
    KeyWords.IS,
    KeyWords.JOIN,
    KeyWords.LEFT,
    KeyWords.LIKE,
    KeyWords.LOCALTIME,
    KeyWords.LOCALTIMESTAMP,
    KeyWords.NATURAL,
    KeyWords.NORMALIZE,
    KeyWords.NOT,
    KeyWords.NULL,
    KeyWords.ON,
    KeyWords.OR,
    KeyWords.ORDER,
    KeyWords.OUTER,
    KeyWords.PREPARE,
    KeyWords.RECURSIVE,
    KeyWords.RIGHT,
    KeyWords.ROLLUP,
    KeyWords.SELECT,
    KeyWords.TABLE,
    KeyWords.THEN,
    KeyWords.TRUE,
    KeyWords.UESCAPE,
    KeyWords.UNION,
    KeyWords.UNNEST,
    KeyWords.USING,
    KeyWords.VALUES,
    KeyWords.WHEN,
    KeyWords.WHERE,
    KeyWords.WITH
  )
end Octopus
