[package]
name = "octopus-common"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }

[build-dependencies]
